apiVersion: apps/v1
kind: Deployment
metadata:
   name: appid-sample-deployment
   namespace: default
spec:
   revisionHistoryLimit: 10
   minReadySeconds: 10
   selector:
     matchLabels:
       microservice: appid-sample
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 3
   replicas: 1
   template:
      metadata:
         labels:
            microservice: appid-sample
      spec:
         containers:
         - name: appid-sample
           image: "us.icr.io/prady/appid-sample:1" # <-- edit here
           ports:
           - containerPort: 80
           env:
           - name: redirectUri
             value: "http://159.122.174.13:30000/ibm/cloud/appid/callback" # <-- edit here
           - name: APPID_SERVICE_BINDING
             valueFrom:
               secretKeyRef:
                 name: binding-appid-demo # <-- edit here
                 key: binding
         imagePullSecrets:
           - name: pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: appid-sample-service
spec:
  selector:
    microservice: appid-sample
  type: NodePort
  ports:
   - port: 80
     nodePort: 30000
     # In an IBM Cloud Container Service Lite Cluster, we have to create the services with Node ports that have non standard ports in the 30000-32767 range.